/* Generated By:JavaCC: Do not edit this line. Compilador.java */
import java.io.*;

public class Compilador implements CompiladorConstants {
  public static void main(String args []) throws ParseException
  {
    Compilador analisador = null;
    try
    {
      analisador = new Compilador(new FileInputStream("prog_fonte.my"));
      analisador.inicio();
    }
    catch (FileNotFoundException e)
    {
      System.out.println("Erro: arquivo nao encontrado");
    }
    catch (TokenMgrError e)
    {
      System.out.println("Erro lexico" + e.getMessage());
    }
    catch (ParseException e)
    {
      System.out.println("Erro sintatico" + e.getMessage());
    }
  }

  static final public void inicio() throws ParseException {
    trace_call("inicio");
    try {
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case STRING_TYPE:
        case INTEGER_TYPE:
        case READ:
        case PRINT:
        case IF:
        case WHILE:
        case IDENT:
        case STRING:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        linhaComando();
      }
      jj_consume_token(0);
    } finally {
      trace_return("inicio");
    }
  }

  static final public void linhaComando() throws ParseException {
    trace_call("linhaComando");
    try {
      comando();
      jj_consume_token(PT_VIRG);
    } finally {
      trace_return("linhaComando");
    }
  }

  static final public void comando() throws ParseException {
    trace_call("comando");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING_TYPE:
      case INTEGER_TYPE:
        declararVar();
        break;
      case IDENT:
        atribuirVar();
        break;
      case PRINT:
        print();
        break;
      case READ:
        read();
        break;
      case STRING:
        concat();
        break;
      case WHILE:
        whileComando();
        break;
      case IF:
        ifComando();
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("comando");
    }
  }

  static final public void declararVar() throws ParseException {
    trace_call("declararVar");
    try {
      type();
      atribuirVar();
    } finally {
      trace_return("declararVar");
    }
  }

  static final public void atribuirVar() throws ParseException {
    trace_call("atribuirVar");
    try {
      jj_consume_token(IDENT);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ATRIB:
        jj_consume_token(ATRIB);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case STRING:
          jj_consume_token(STRING);
          break;
        case IDENT:
        case INTEGER:
          expressao();
          break;
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[3] = jj_gen;
        ;
      }
    } finally {
      trace_return("atribuirVar");
    }
  }

  static final public void concat() throws ParseException {
    trace_call("concat");
    try {
      jj_consume_token(STRING);
      label_2:
      while (true) {
        jj_consume_token(CONCATENAR);
        jj_consume_token(STRING);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CONCATENAR:
          ;
          break;
        default:
          jj_la1[4] = jj_gen;
          break label_2;
        }
      }
    } finally {
      trace_return("concat");
    }
  }

  static final public void ifComando() throws ParseException {
    trace_call("ifComando");
    try {
      jj_consume_token(IF);
      jj_consume_token(PAR_E);
      condicao();
      jj_consume_token(PAR_D);
      jj_consume_token(ENTAO);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case STRING_TYPE:
        case INTEGER_TYPE:
        case READ:
        case PRINT:
        case IF:
        case WHILE:
        case IDENT:
        case STRING:
          ;
          break;
        default:
          jj_la1[5] = jj_gen;
          break label_3;
        }
        linhaComando();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ELSE:
        jj_consume_token(ELSE);
        label_4:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case STRING_TYPE:
          case INTEGER_TYPE:
          case READ:
          case PRINT:
          case IF:
          case WHILE:
          case IDENT:
          case STRING:
            ;
            break;
          default:
            jj_la1[6] = jj_gen;
            break label_4;
          }
          linhaComando();
        }
        break;
      default:
        jj_la1[7] = jj_gen;
        ;
      }
      jj_consume_token(ENDIF);
    } finally {
      trace_return("ifComando");
    }
  }

  static final public void whileComando() throws ParseException {
    trace_call("whileComando");
    try {
      jj_consume_token(WHILE);
      jj_consume_token(PAR_E);
      condicao();
      jj_consume_token(PAR_D);
      label_5:
      while (true) {
        linhaComando();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case STRING_TYPE:
        case INTEGER_TYPE:
        case READ:
        case PRINT:
        case IF:
        case WHILE:
        case IDENT:
        case STRING:
          ;
          break;
        default:
          jj_la1[8] = jj_gen;
          break label_5;
        }
      }
      jj_consume_token(ENDWHILE);
    } finally {
      trace_return("whileComando");
    }
  }

  static final public void condicao() throws ParseException {
    trace_call("condicao");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER:
        expressaoBool();
        label_6:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case IGUAL:
          case MAIOR_IGUAL:
          case MENOR_IGUAL:
          case DIFERENTE:
          case SC_AND:
          case SC_OR:
          case NEGACAO:
            ;
            break;
          default:
            jj_la1[9] = jj_gen;
            break label_6;
          }
          operadorBool();
          jj_consume_token(PAR_E);
          label_7:
          while (true) {
            condicao();
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case INTEGER:
            case PAR_E:
              ;
              break;
            default:
              jj_la1[10] = jj_gen;
              break label_7;
            }
          }
          jj_consume_token(PAR_D);
        }
        break;
      case PAR_E:
        jj_consume_token(PAR_E);
        label_8:
        while (true) {
          condicao();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case INTEGER:
          case PAR_E:
            ;
            break;
          default:
            jj_la1[11] = jj_gen;
            break label_8;
          }
        }
        jj_consume_token(PAR_D);
        label_9:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case IGUAL:
          case MAIOR_IGUAL:
          case MENOR_IGUAL:
          case DIFERENTE:
          case SC_AND:
          case SC_OR:
          case NEGACAO:
            ;
            break;
          default:
            jj_la1[12] = jj_gen;
            break label_9;
          }
          operadorBool();
        }
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("condicao");
    }
  }

  static final public void type() throws ParseException {
    trace_call("type");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING_TYPE:
        jj_consume_token(STRING_TYPE);
        break;
      case INTEGER_TYPE:
        jj_consume_token(INTEGER_TYPE);
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("type");
    }
  }

  static final public void expressao() throws ParseException {
    trace_call("expressao");
    try {
      fator();
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MAIS:
        case MENOS:
        case MULT:
        case DIVID:
        case POT:
          ;
          break;
        default:
          jj_la1[15] = jj_gen;
          break label_10;
        }
        operador();
        fator();
      }
    } finally {
      trace_return("expressao");
    }
  }

  static final public void expressaoBool() throws ParseException {
    trace_call("expressaoBool");
    try {
      fatorBool();
      operadorBool();
      fatorBool();
    } finally {
      trace_return("expressaoBool");
    }
  }

  static final public void fatorBool() throws ParseException {
    trace_call("fatorBool");
    try {
      jj_consume_token(INTEGER);
    } finally {
      trace_return("fatorBool");
    }
  }

  static final public void operadorBool() throws ParseException {
    trace_call("operadorBool");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IGUAL:
        jj_consume_token(IGUAL);
        break;
      case MAIOR_IGUAL:
        jj_consume_token(MAIOR_IGUAL);
        break;
      case MENOR_IGUAL:
        jj_consume_token(MENOR_IGUAL);
        break;
      case DIFERENTE:
        jj_consume_token(DIFERENTE);
        break;
      case SC_AND:
        jj_consume_token(SC_AND);
        break;
      case SC_OR:
        jj_consume_token(SC_OR);
        break;
      case NEGACAO:
        jj_consume_token(NEGACAO);
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("operadorBool");
    }
  }

  static final public void fator() throws ParseException {
    trace_call("fator");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENT:
        jj_consume_token(IDENT);
        break;
      case INTEGER:
        jj_consume_token(INTEGER);
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("fator");
    }
  }

  static final public void operador() throws ParseException {
    trace_call("operador");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MAIS:
        jj_consume_token(MAIS);
        break;
      case MENOS:
        jj_consume_token(MENOS);
        break;
      case MULT:
        jj_consume_token(MULT);
        break;
      case DIVID:
        jj_consume_token(DIVID);
        break;
      case POT:
        jj_consume_token(POT);
        break;
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("operador");
    }
  }

  static final public void print() throws ParseException {
    trace_call("print");
    try {
      jj_consume_token(PRINT);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENT:
      case INTEGER:
        expressao();
        break;
      case STRING:
        jj_consume_token(STRING);
        break;
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("print");
    }
  }

  static final public void read() throws ParseException {
    trace_call("read");
    try {
      jj_consume_token(READ);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING_TYPE:
      case INTEGER_TYPE:
        type();
        break;
      default:
        jj_la1[20] = jj_gen;
        ;
      }
      jj_consume_token(IDENT);
    } finally {
      trace_return("read");
    }
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public CompiladorTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[21];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xc8f800,0xc8f800,0x1c00000,0x400,0x0,0xc8f800,0xc8f800,0x20000,0xc8f800,0x0,0x1000000,0x1000000,0x0,0x1000000,0x1800,0xf8000000,0x0,0x1400000,0xf8000000,0x1c00000,0x1800,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x7f,0x100,0x100,0x7f,0x100,0x0,0x0,0x7f,0x0,0x0,0x0,0x0,};
   }

  /** Constructor with InputStream. */
  public Compilador(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Compilador(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CompiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Compilador(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CompiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Compilador(CompiladorTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CompiladorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      trace_token(token, "");
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
      trace_token(token, " (in getNextToken)");
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[42];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 21; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 42; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  static private int trace_indent = 0;
  static private boolean trace_enabled = true;

/** Enable tracing. */
  static final public void enable_tracing() {
    trace_enabled = true;
  }

/** Disable tracing. */
  static final public void disable_tracing() {
    trace_enabled = false;
  }

  static private void trace_call(String s) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Call:   " + s);
    }
    trace_indent = trace_indent + 2;
  }

  static private void trace_return(String s) {
    trace_indent = trace_indent - 2;
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Return: " + s);
    }
  }

  static private void trace_token(Token t, String where) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Consumed token: <" + tokenImage[t.kind]);
      if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
        System.out.print(": \"" + t.image + "\"");
      }
      System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
    }
  }

  static private void trace_scan(Token t1, int t2) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Visited token: <" + tokenImage[t1.kind]);
      if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
        System.out.print(": \"" + t1.image + "\"");
      }
      System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
    }
  }

}
