/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIBE = 7;
  /** RegularExpression Id. */
  int COMMENT = 8;
  /** RegularExpression Id. */
  int PT_VIRG = 9;
  /** RegularExpression Id. */
  int ATRIB = 10;
  /** RegularExpression Id. */
  int STRING_TYPE = 11;
  /** RegularExpression Id. */
  int INTEGER_TYPE = 12;
  /** RegularExpression Id. */
  int READ = 13;
  /** RegularExpression Id. */
  int PRINT = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int ENTAO = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int ENDIF = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int ENDWHILE = 21;
  /** RegularExpression Id. */
  int IDENT = 22;
  /** RegularExpression Id. */
  int STRING = 23;
  /** RegularExpression Id. */
  int INTEGER = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;
  /** RegularExpression Id. */
  int LETTER = 26;
  /** RegularExpression Id. */
  int MAIS = 27;
  /** RegularExpression Id. */
  int MENOS = 28;
  /** RegularExpression Id. */
  int MULT = 29;
  /** RegularExpression Id. */
  int DIVID = 30;
  /** RegularExpression Id. */
  int POT = 31;
  /** RegularExpression Id. */
  int IGUAL = 32;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 33;
  /** RegularExpression Id. */
  int MAIOR = 34;
  /** RegularExpression Id. */
  int MENOR = 35;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 36;
  /** RegularExpression Id. */
  int DIFERENTE = 37;
  /** RegularExpression Id. */
  int SC_AND = 38;
  /** RegularExpression Id. */
  int SC_OR = 39;
  /** RegularExpression Id. */
  int NEGACAO = 40;
  /** RegularExpression Id. */
  int CONCATENAR = 41;
  /** RegularExpression Id. */
  int PAR_E = 42;
  /** RegularExpression Id. */
  int PAR_D = 43;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int comentario = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "\"exibe\"",
    "\"//\"",
    "\";\"",
    "\":=\"",
    "\"string\"",
    "\"integer\"",
    "\"read\"",
    "\"print\"",
    "\"if\"",
    "\"entao\"",
    "\"else\"",
    "\"endIf\"",
    "\"while\"",
    "\"do\"",
    "\"endWhile\"",
    "<IDENT>",
    "<STRING>",
    "<INTEGER>",
    "<DIGIT>",
    "<LETTER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"==\"",
    "\">=\"",
    "\">\"",
    "\"< \"",
    "\"<=\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"#\"",
    "\"(\"",
    "\")\"",
  };

}
