/* Generated By:JavaCC: Do not edit this line. CompiladorExemploConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorExemploConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIBE = 7;
  /** RegularExpression Id. */
  int COMMENT = 8;
  /** RegularExpression Id. */
  int PT_VIRG = 9;
  /** RegularExpression Id. */
  int ATRIB = 10;
  /** RegularExpression Id. */
  int STRING_TYPE = 11;
  /** RegularExpression Id. */
  int INTEGER_TYPE = 12;
  /** RegularExpression Id. */
  int IDENT = 13;
  /** RegularExpression Id. */
  int STRING = 14;
  /** RegularExpression Id. */
  int INTEGER = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int LETTER = 17;
  /** RegularExpression Id. */
  int MAIS = 18;
  /** RegularExpression Id. */
  int MENOS = 19;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int comentario = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "\"exibe\"",
    "\"//\"",
    "\";\"",
    "\":=\"",
    "\"string\"",
    "\"integer\"",
    "<IDENT>",
    "<STRING>",
    "<INTEGER>",
    "<DIGIT>",
    "<LETTER>",
    "\"+\"",
    "\"-\"",
  };

}
